### ISSUE TITLE
[ENHANCEMENT] Loop until cancel

### ISSUE THREAD

**Issue by alcgabriel** [Asthestarsfalll/img2art#1]
this is INSANE, but you can make some loop until we cancel? or add a label of seconds for the time we want to see the art
--time-to-end Xs
or after pressing ctrl c to stop

https://github.com/Asthestarsfalll/img2art/assets/85556196/b498d2eb-289e-4ce2-8f7b-e0c3644bb653

**Comment by Asthestarsfalll** [comment]
Hi, you can use a script to do this:
```sh
#!/bin/sh

filename=$1 

temp_line=""
output_array=()

while IFS= read -r line
do
  if [ "$line" == "" ] 
  then
    output_array+=("$temp_line")
    temp_line=""
  else
    temp_line+="$line"
    temp_line+="\n"
  fi
done < "$filename"

while true; do
  for frame in "${output_array[@]}" 
  do
      clear
      echo -e "$frame"
      sleep 0.05
  done
done
```

Pass the generated txt to the scripts.

**Comment by Asthestarsfalll** [comment]
I add this to img2art, now you can add `--loop` to do this. I have not published it on pypi. So you can clone this repo and run `poetry install`.
